### ISSUE TITLE
FYI/Crash Report

### ISSUE THREAD

**Issue by Nexusdog** [TheRandomLabs/RandomTweaks#11]
https://pastebin.com/69TEVp0F

**Comment by TheRandomLabs** [comment]
Damn, and I thought I'd gotten all the crashes. Sorry about this, I'm not great at testing it seems. Thanks for reporting though.

**Comment by TheRandomLabs** [comment]
I believe it's fixed now. I tested it on three different versions of MC with the configs deleted.
