### ISSUE TITLE
No auto third person for elytra

### ISSUE THREAD

**Issue by flannerby** [TheRandomLabs/RandomTweaks#13]
The auto third person feature does not work for elytra flight. All other parts auto switch, however when flying with an elytra there is no switch and in addition you cannot change perspectives with F5 until flight has ended. The other things such as boat and minecart you can use F5 to exit third person while riding a horse. I have tested this on every version since the feature was released and also on the oldest, latest and recommended versions of forge for 1.12.2.

**Comment by TheRandomLabs** [comment]
Thanks for reporting this and for testing it in so many different environments even though it wasn't really necessary. :wink:

**Comment by TheRandomLabs** [comment]
See if 1.18.2.0 fixes this once it's on CurseForge. It worked for me in testing.

**Comment by flannerby** [comment]
issue resolved, thanks!
