### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by SjetCraft** [TheRandomLabs/RandomTweaks#14]
Forge: 14.23.3.2655 
Version: 1.12.2-1.18.2.0 

Crash on loading. I have tried deleting the configs but still have the same crash.

[gist link](https://gist.github.com/SjetCraft/65ace7ffcb5bf1169ac4f8e09a21e8de)

**Comment by TheRandomLabs** [comment]
Strange. Should be an easy fix though.
