### ISSUE TITLE
Forge 1.12.2-14.23.2.2647 breaks dimension unloading

### ISSUE THREAD

**Issue by evhub** [TheRandomLabs/RandomTweaks#15]
Same issue as https://github.com/Unnoen/Unloader/issues/2. I tried swapping out Unloader for RandomTweaks on the new forge and encountered the same problem as described in the Unloader issue.

**Comment by TheRandomLabs** [comment]
As far as I can tell, Forge did implement this feature. Are these dimensions taking any tick time?

**Comment by TheRandomLabs** [comment]
I just tested it with RandomTweaks' dimension unloading feature disabled, and the Nether and the End were automatically unloaded and didn't show up in the /forge tps list. Is it possible that the dimension mods are preventing unloading?

**Comment by TheRandomLabs** [comment]
I'll remove the unloader feature since it's already in Forge.
