### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Nexusdog** [TheRandomLabs/RandomTweaks#17]
MC/F 1.12.2/2707

Latest version falls over, 11911 works fine.

https://pastebin.com/j8GKctyz

Need more coffee, just woke up!

**Comment by TheRandomLabs** [comment]
You should reset your configuration or just remove "respawnBehavior" in the "hunger" section. I'll probably just rename it to avoid incompatibilities, but to be honest I thought I already had renamed it to something else.
