### ISSUE TITLE
Multicraft server console spam about falling blocks.

### ISSUE THREAD

**Issue by Darkmega18** [TheRandomLabs/RandomTweaks#21]
just an endless amount of these logs coming up in my server console right now.

https://pastebin.com/hdhK5A4t

I disabled random patches and they stopped after a reload. Since it was probably one of the only things I added in recent memory that could do something of the sort.

edit: eh. crap, it came back and now it's about "minecraft:item"... :V nvm. unless you might know what could be causing it?

**Comment by TheRandomLabs** [comment]
My mod shouldn't be doing anything like that. To ensure it wasn't a fluke,
could you try readding the mod and seeing if it still occurs?

**Comment by TheRandomLabs** [comment]
Sorry, I have no idea what might be causing it.
