### ISSUE TITLE
Forever loading with void world generator (1.12.2)

### ISSUE THREAD

**Issue by mchorse** [TheRandomLabs/RandomTweaks#22]
Hello there!

There is an issue with Void world generator. When I create a world with this world generator, it's starts generating and when it reaches "Loading world", it just freezes. Freezes as in doesn't do anything. The status of Minecraft doesn't become "(not responding)," it's just freezes.

Here is a [debug.log](https://github.com/TheRandomLabs/RandomTweaks/files/2194204/debug.log), if you want to take a look at it. Although it doesn't seem to yield any exceptions or errors. 

I would really appreciate if you could fix this, because that seems like a very useful world for messing around with no terrain at all 🙂

**Comment by TheRandomLabs** [comment]
Could you install the latest version of RandomTweaks and try again? I may
have fixed a similar issue already.

**Comment by mchorse** [comment]
No, unfortunately, it didn't solved the issue. It's still freezing whenever I try to load or create a new void world.

**Comment by TheRandomLabs** [comment]
Alright, I'll take a look at it.

**Comment by TheRandomLabs** [comment]
I haven't been able to reproduce this issue. Does the game freeze while loading Void Islands or Realistic worlds as well?

**Comment by mchorse** [comment]
Hmm, that's weird. Game doesn't freezes with Realistic world, but I decided to disable few of my mods, and did a few additional tests, and Void works if I remove some of my mods.

I don't know what exactly causing this, but... apparently **Teletubbies** mod causes the game to freeze 😂

I'm sorry for disturbing you with such a stupid thing 🤣

**Comment by TheRandomLabs** [comment]
Great, I'll have a look at the Teletubbies mod tomorrow.

**Comment by mchorse** [comment]
I took a look at it, and looks like the issue is in `GenTubbyVoiceTrumpet` class:

```java
    /* func_180495_p = getBlockState(), func_177230_c = getBlock() */
    while ((world.func_180495_p(pos).func_177230_c() instanceof BlockAir))
    {
      yCoord--;
      pos = new BlockPos(xCoord, yCoord, zCoord);
    }
```

I think it gets stuck over here. I'll report that to Teletubbies mod dev.

**Comment by TheRandomLabs** [comment]
Yeah, the author forgot to exit the loop if Y reaches 0. I'm not sure if there's something I should do differently, but I've reported it to the author as well.

**Comment by mchorse** [comment]
I think your mod is fine, thanks for working on this issue with me, sorry if I disturbed you 😁
