### ISSUE TITLE
Requires a non-Recommended Forge version

### ISSUE THREAD

**Issue by acook** [TheRandomLabs/RandomTweaks#23]
Forge version mismatches can be problematic for some mods so I tend to stick with the Recommended release.

RandomTweaks since https://github.com/TheRandomLabs/RandomTweaks/commit/63efd7d9398f43784745e908746529aa196a4b50 requires `14.23.4.2718`. 

Of all the mods in my modpack, RandomTweaks is the only one which requires a newer version of Forge then the recommended release. Does RandomTweaks v2.1.1.0+ explicitly rely on behaviour from the newer version of Forge?

**Comment by TheRandomLabs** [comment]
Yes, but I can work around it.

**Comment by acook** [comment]
I would appreciate it if so, I would like to use the newer versions of RandomTweaks. 👍

**Comment by TheRandomLabs** [comment]
Yeah, I'll work on it today or tomorrow.
