### ISSUE TITLE
Shift + F4 keybind overlaps with vanilla F3 command

### ISSUE THREAD

**Issue by TehTemmie** [TheRandomLabs/RandomTweaks#24]
In case you are not aware, you can already switch between Creative and Spectator mode in vanilla Minecraft by pressing F3 + N, and the Shift + F4 keybind in your mod seems to do the exact same thing. I understand if you added the keybind for players who don't know about F3 + N, or so players can have a customizeable keybind to toggle between Creative and Spectator mode, but I thought I'd let you know about this.

**Comment by TheRandomLabs** [comment]
Thanks for letting me know. I'll keep the keybind but leave it unbound by
default.
