### ISSUE TITLE
Foods give incorrect saturation.

### ISSUE THREAD

**Issue by Lartza** [TheRandomLabs/RandomTweaks#26]
With or without AppleCore installed, eating foods gives too small saturation values compared to the values AppleSkin shows.

There are some screenshots of this happening on https://github.com/AllTheMods/ATM3-Remix/issues/26#issuecomment-419666687

The small instance I tested this myself was Forge 14.23.4.2760, AppleSkin-mc1.12-1.0.9, randomtweaks-1.12.2-2.1.3.1 and optionally AppleCore-mc1.12.2-3.1.4

**Comment by Lartza** [comment]
Could this possibly be as simple as a missing multiplication by 2f?

Specifically from this line https://github.com/TheRandomLabs/RandomTweaks/blob/077dbfcaf532a2b04d95d284acac96e01f5605f4/src/main/java/com/therandomlabs/randomtweaks/common/RTFoodStats.java#L82

I'm going by the example code at https://github.com/squeek502/AppleCore/issues/121#issuecomment-387230933

**Comment by TheRandomLabs** [comment]
Oops, it is. This will be fixed in 1.12.2-2.1.3.2.
