### ISSUE TITLE
Crash on loading if forced world generation is enabled and conflicting with another world gen mod doing the same. 

### ISSUE THREAD

**Issue by DWX12** [TheRandomLabs/RandomTweaks#27]
Long story short, if there's another mod that also has a forced world gen setting enabled, the game will crash on loading. The only suggestion I have to avoid this issue is a warning, upon load, if RandomPatches can detect another mod is trying to force world gen as well.

I encountered this with Hexlands and am glad I had thought that this was the issue.

Great mod. Thank you or all of your hard work and effort, it's well appreciated.

Edit:
This is after trying to load Minecraft with the realistic world gen set to false and still got a crash:
https://paste.dimdev.org/difaroxuha.mccrash

Apparently I read it incorrectly and it doesn't force world generation of a specific type if any of the configs are set to true; however, Hexlands does if that config is set to true. And by force, I mean if you start up a default world the generation will be Hexlands or BOPHexlands if you tell it to do so in the config.

Edit 2:
Seems to only crash if this is set to true:
Force overworld hex generation even when world type is not selected
Default: false
B:forceHexGen=false

I also have the dimension set to 0:
What dimension ID to use
Default: 88
I:dimID=0

**Comment by TheRandomLabs** [comment]
Interesting, looks like Hex Lands [changes](https://github.com/superfluke/hexlands/blob/690980590f110ad1290492e985a12c5dbd476ef6/src/main/java/fluke/hexlands/HexServer.java#L37) the `WORLD_TYPES` array so that it only accepts `WorldTypeHexLands`. This is fixed in 1.12.2-2.1.7.1.

**Comment by DWX12** [comment]
Many thanks, you're quick. Again, sorry about posting issue on the wrong mod, lol.

**Comment by TheRandomLabs** [comment]
It's fine, haha. You forgot to change RandomPatches to RandomTweaks here as well. It might take a bit for it to be accepted on CurseForge.
