### ISSUE TITLE
disableCumulativeAnvilCost not working

### ISSUE THREAD

**Issue by neoc666** [TheRandomLabs/RandomTweaks#28]
StoneBlock 1.0.20
randomtweaks-1.12.2-2.1.7.0

As I understand this option, it prevents the repair costs (in XP levels) from getting higher and higher every time you repair an item. This doesn't work. I even checked the NBT tag for a pickaxe.

If that's not what this option is meant for please document it properly because I have no idea what else could be meant by "cumulative cost".

**Comment by TheRandomLabs** [comment]
I made a small typo, sorry. This will be fixed in 2.1.9.0.

**Comment by neoc666** [comment]
Thanks!
