### ISSUE TITLE
have you forget sign the jar?

### ISSUE THREAD

**Issue by arnesacnussem** [TheRandomLabs/RandomTweaks#29]
![image](https://user-images.githubusercontent.com/9441546/47796746-e9dce680-dd5f-11e8-9369-3c85d34c5000.png)
want to run that on a forge server,but as the pic says.
tried update,but nothing help 

![image](https://user-images.githubusercontent.com/9441546/47796970-6243a780-dd60-11e8-8039-100522102ac1.png)
and nothing wrong with file md5

**Comment by TheRandomLabs** [comment]
I've tried to fix this issue before, but I'll look into it again. It's nothing urgent as long as it doesn't crash.

**Comment by arnesacnussem** [comment]
you're right,
but is there an easy way to skip forge signature verify?

seems the verify fail only occurred on forge server,not on forge client?

**Comment by TheRandomLabs** [comment]
The error also occurs on the client; you can see in the log.
**EDIT:** This is fixed in RandomTweaks 1.12.2-2.2.0.2.
