### ISSUE TITLE
[1.10.2] Issue with translations being incorrect.

### ISSUE THREAD

**Issue by DeadSix27** [TheRandomLabs/RandomTweaks#3]
Version: `randomtweaks-1.11.2-1.2.0.0.jar`
Forge: `forge-1.10.2-12.18.3.2234-universal`

If this mod is loaded, it messes with the translations of a lot of other mods, including forge itself.

Command replies etc  appear only as the placeholder string.

As seen in here: (I actually reported this issue to forge itself as I couldn't figure out at all what causes it)

https://github.com/MinecraftForge/MinecraftForge/issues/3722

EDIT: This issue still exist, the fix in the above issue is for 1.11 and something different.

**Comment by TheRandomLabs** [comment]
I was having this issue in my modpack myself, but I couldn't figure out what was causing it. :P

**Comment by TheRandomLabs** [comment]
Just to clarify, the fix in the above issue didn't work for RandomTweaks on 1.11.2?

**Comment by TheRandomLabs** [comment]
Never mind, I think I found the issue. I wasn't copying over the old localizations when I replaced the code that handles them.
