### ISSUE TITLE
[1.12.2] Crash on Gamestart (SoundEngine)

### ISSUE THREAD

**Issue by MasterEnderman** [TheRandomLabs/RandomTweaks#30]
Crash Report: https://pastebin.com/cRJ5EGMk
Forge: 14.23.5.2769
RandomTweaks: 2.2.0.3

**Comment by TheRandomLabs** [comment]
Does this issue occur without RandomTweaks?

**Comment by MasterEnderman** [comment]
Yes. But i got another problem, if a player on a server tries to sleep at night the server crashes:
https://pastebin.com/hpAvunj9

**Comment by TheRandomLabs** [comment]
RandomTweaks should not be causing this. Does this issue also occur without RandomTweaks?

**Comment by MasterEnderman** [comment]
Yes it does. Well, guess i have to continue my search. Sorry.
