### ISSUE TITLE
[Crash] When opening the controls menu, Minecraft crashes.

### ISSUE THREAD

**Issue by Qonsyuma** [TheRandomLabs/RandomTweaks#32]
As I said in the title, this problem has been existing for me since multiple versions of this mod
( This crash also occurs without any other mods enabled, forge version is: 1.12.2-14.23.5.2796 )

If a crash log is needed, I'll be happy to DM it to the person needed

**Comment by TheRandomLabs** [comment]
I can't reproduce this issue. Can I have a crash log?

**Comment by Qonsyuma** [comment]
Sent over CurseForge!

**Comment by TheRandomLabs** [comment]
I still have no idea why that's happening. However, I've attempted a fix which should be in 1.12.2-2.3.0.4 once I fix #33 and #34.

**Comment by TheRandomLabs** [comment]
I've figured out why the crash is occurring. This is fixed in 1.12.2-2.4.0.1.

**Comment by Qonsyuma** [comment]
Thank's a lot! :)

**Comment by TheRandomLabs** [comment]
No problem.
