### ISSUE TITLE
[Functionality Broken] Specifying the biome type for Void Island world fails

### ISSUE THREAD

**Issue by Dragnier** [TheRandomLabs/RandomTweaks#33]
Whether the config is empty, minecraft:plains, plains, or any other setting; Biome generates randomly. I did notice that setting it to just plains made Journeymap display the biome as Plains until I moved; when it then changed to the correct biome type of deep ocean. I do not think your code is actually setting the biome properly.

I would suggest also allowing blacklisting biomes along with random generation if you can pull that off.

**Comment by TheRandomLabs** [comment]
Actually, I wasn't setting the biome at all. Whoops.

I'll add a biome blacklist.

**Comment by TheRandomLabs** [comment]
This is done in 1.12.2-2.4.0.0.
