### ISSUE TITLE
[Suggestion] Migrate settings

### ISSUE THREAD

**Issue by ghost** [TheRandomLabs/RandomTweaks#35]
When a config file is updated with a mod update, it is preferential to migrate settings over instead of forcing pack creators to go through and manually reapply all custom settings to the new file, many of which have a new location.

**Comment by TheRandomLabs** [comment]
I'll try to do this the next time I make a major change to the configuration, but hopefully I don't have to do that for a while.

**Comment by TheRandomLabs** [comment]
I've implemented a property migration system in the new [configuration management library](https://github.com/TheRandomLabs/RandomLib) I'm using, so this should no longer be an issue.
