### ISSUE TITLE
Suggestion: More Attack speed configuration/Combat configuration

### ISSUE THREAD

**Issue by SirAron111** [TheRandomLabs/RandomTweaks#36]
"Option to set the base attack speed for players. Try setting this to 24.0 to remove the attack cooldown"

I really like the option to change the attack speed in general despite the small bug that causes some items to literally not recharge the attack speed meter at all when setting the attack speed lower than 3.
And I would really like to ask if it is possible to add 2 more options to this.

Config Option 1:
Would be to disable weapon swinging (attacking mobs) when the attack speed meter inst fully charged. This would make for some interesting changes and prevent players from spamming attacks like in the old minecraft versions. Or at least turn off dmg from player during that time of recharging.

Config Option 2:
Setting the attack speed individually for selected weapon types! This way you could in vanilla for example make axes faster and swords slower or something like that. But most of all it would benefit any modpack that uses mods that add weapons like “Tinkers Construct” and its add-ons like “Plustic” etc. As these add a lot of swords that have different base attack speeds. Like normal sword is slower than a rapier or a katana (but it shouldn’t as it makes these really op in comparison especially since people can just spam click them since the option I first mentioned doesn’t exist yet). 

Would it be possible to add such configs?

For example in my modpack “Dimension Zero” I am looking for a way to be able to configure the attack speed like that so people can still fight and I don’t make normal swords useless by setting the general attack speed lower but atm people just build katanas and rapiers and just spam click nuking any mob even if it has 1000+ hp. If I could somehow configure these 2 things it would be awesome. I have your Mod in my pack already and I noticed the attack speed changes you can already make. As many other mod makers told me they can’t change attack speed due to some coding they don’t understand I was hoping it could be done here since it already is configurable to some extend here.

Thx in advance for reading this.

**Comment by TheRandomLabs** [comment]
Sorry for the late response. I've implemented the first option and will consider the second option for RandomConfigs.

**Comment by SirAron111** [comment]
Thx for responding at all. The first option was already made as a mod by someone who also thought this was a good idea it’s called exhausted stamina made by tag3. Simple but useful mod! https://minecraft.curseforge.com/projects/exhausted-stamina?gameCategorySlug=mc-mods&projectID=309874

The Second option is quiet hard to make happen and many people gave up on it If you actually manage to do it this would be awesome as it is one of the most needed features for my Modpack https://authors.curseforge.com/forums/bounty-board/minecraft/237468-hard-to-make-mod-idea-that-no-one-seems-to-be-able and https://authors.curseforge.com/forums/bounty-board/minecraft/237469-mod-idea-for-a-hostile-environment-mod are the only ones left.

**Comment by TheRandomLabs** [comment]
That's surprising, since it should actually be pretty simple. To prove it, I'll add it to RandomConfigs now.

**Comment by TheRandomLabs** [comment]
[Done.](https://minecraft.curseforge.com/projects/randomconfigs) I'll probably port it up to 1.13 and 1.14 as well.
