### ISSUE TITLE
[BUG] No startup sound

### ISSUE THREAD

**Issue by ghost** [TheRandomLabs/RandomTweaks#37]
Forge: 2768
Dynamic Surroundings: 3.4.10.5
Random Tweaks: 2.4.0.2

After doing my usual round of mod updates, the startup sound fails to play. The world load sound works fine, so I'm not putting it in wrong. It worked fine in 2.2.1.1. I do have the specific option for dynamic surroundings set to true, but it doesn't play when in focus either, so I don't think that's the issue.

Here's the config: 
[randomtweaks.txt](https://github.com/TheRandomLabs/RandomTweaks/files/2707713/randomtweaks.txt)

**Comment by TheRandomLabs** [comment]
I can't reproduce this issue with Dynamic Surroundings 3.4.10.5 or 3.5.4.0BETA. Does it work if you use a different startup sound?

**Comment by ghost** [comment]
Nope. Picked a random one from the list and threw it in with no change. Is there anything else you're aware of that could cause it to not work?

I also tried deleting the config to see if something in it was defective (I've seen things), didn't help.

edit: disabled dynamic surroundings, problem fixed. My hacky fix to the startup sound from that mod also having a startup sound that cannot be disabled was to put minecraft:potato (doesn't exist) as the sound as leaving it blank causes it to reset. I guess this caught up to me as things are now loading in a different order and it broke. I'll close this and go make a post over there so that a proper disable can be implemented.

[-Issue Moved-> https://github.com/OreCruncher/DynamicSurroundings/issues/431

**Comment by TheRandomLabs** [comment]
Oh, if Dynamic Surroundings' startup sound list isn't empty, RandomTweaks doesn't play its startup sound to avoid conflicts.

**Comment by TheRandomLabs** [comment]
```
    # Possible sounds to play when client reaches main game menu [default: [minecraft:entity.experience_orb.pickup], [minecraft:entity.chicken.egg]]
    S:"Startup Sound List" <
     >
```
works for me.

**Comment by ghost** [comment]
Actually believe it or not, it was playing fine with an invalid sound set in the dsurround config and one set in randomtweaks, at least until I updated things and then something started caring.

I'll give that fix a try, but last time I tried doing that dsurround just reset that line in the config because it didn't like me deleting it.

Edit: well this time it let me delete the line and it stayed that way. Thanks for the assistance :D
