### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by KAfable** [TheRandomLabs/RandomTweaks#38]
https://gist.github.com/Vyraal1/226618ad0a7adb0f0e52199097750513

This is in a pack-dev environment for FTB Interactions, was checking worldgen in a nearby swamp and used Worldstripper to check oregen, deleteing some water blocks. Not sure if any of those are related.

**Comment by TheRandomLabs** [comment]
I'm not sure what could be causing this, but iterating through the entity list in a different way should solve this.

**Comment by TheRandomLabs** [comment]
1.12.2-2.4.0.5 probably fixes this.
