### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Nexusdog** [TheRandomLabs/RandomTweaks#39]
MC/F 1.12.2/2796
RT 2405

* I've been unable to get RT working since 2211, but testing subsequent versions, all of which crash. Log looks like it's a Forge issue, but what do I know, I'm just a meaty bag of mostly water.

https://paste.dimdev.org/exizuquxep.mccrash

**Comment by TheRandomLabs** [comment]
The fix will be released once I improve a few configuration options.
EDIT: Uploaded.

**Comment by Nexusdog** [comment]
Cheers lad, much appreciate the prompt response.
