### ISSUE TITLE
[1.11.2-1.6.0.0] Incompatability with Blood Magic (and Guide API)

### ISSUE THREAD

**Issue by Aphyxia** [TheRandomLabs/RandomTweaks#4]
Blood Magic manual text is replaced with similar code instead of the real text.

> guide.bloodmagic.entry.demon.sentientGem.info.1

Crash log (happens when logging into a game with book already opened (without Random Tweaks) - shows blank page and on moving page, it crashes):
http://pastebin.com/gukFmXnC

Minecraft 1.11.2
Forge 2252
Random Tweaks 1.11.2-1.6.0.0
bloodmagic 1.11-2.1.6-75
guideapi 1.11-2.1.0-50

**Comment by TheCodedOne** [comment]
Most likely due to [screwing with the language map](https://github.com/TheRandomLabs/RandomTweaks/blob/master/src/main/java/com/therandomlabs/randomtweaks/common/RTLanguageMap.java)

**Comment by Aphyxia** [comment]
Fixed in 1.7.0.1 of RandomTweaks.
