### ISSUE TITLE
Heads not stacking

### ISSUE THREAD

**Issue by ghost** [TheRandomLabs/RandomTweaks#41]
The heads dropped on death do not stack, seemingly on a session based manner.

**Comment by TheRandomLabs** [comment]
Oh, I was going to look into this a while ago, then completely forgot about it.

**Comment by TheRandomLabs** [comment]
I can fix this, but the fix will have to be in RandomPatches.

**Comment by ghost** [comment]
I have both (as I assume most do). A fitting location for the patch x3

**Comment by TheRandomLabs** [comment]
Fixed in RandomPatches 1.12.2-1.13.0.0. I've marked it as a beta since I don't know if there could be unintended side effects, but I've tested it on 1.8, 1.10 and 1.12.
