### ISSUE TITLE
Suggestion: Remove anvil damage

### ISSUE THREAD

**Issue by IronPiston** [TheRandomLabs/RandomTweaks#43]
In the same vein as disabling anvil level scaling, the option to disable damage to an anvil from using it/dropping on entities or blocks would be appreciated.

**Comment by TheRandomLabs** [comment]
I don't see why not.

**Comment by TheRandomLabs** [comment]
Sorry for the late reply, but I think [Anvil Fix](https://minecraft.curseforge.com/projects/anvil-fix) would do it better than I could.
