### ISSUE TITLE
ding registry sounds continuously reset on restart

### ISSUE THREAD

**Issue by Yoghurt4C** [TheRandomLabs/RandomTweaks#47]
used those lines on 2.4.3.2 with no issues, then updated to 2.5.0.2 and this started happening; for some reason, only the strings are affected, and the pitch/volume doubles don't reset

randomtweaks-1.12.2-2.5.0.2

**Comment by TheRandomLabs** [comment]
Thanks for reporting! This is fixed in 1.12.2-2.5.0.3.
