### ISSUE TITLE
[suggestion] intercept friendly fire on LivingAttackedEvent instead of LivingHurtEvent

### ISSUE THREAD

**Issue by Jackiecrazy** [TheRandomLabs/RandomTweaks#48]
Since it's processed before the damage is actually administered, this means that things relating to being attacked (i.e. turning red and taking knockback) will no longer occur. This helps people without hp bar mods to rest assured that they are not, in fact, damaging their pets, and prevents AoE attacks (e.g. from electroblob's wizardry) from knocking back pets and disrupting their attacks.

**Comment by TheRandomLabs** [comment]
Thanks for the idea!
