### ISSUE TITLE
Why are you disabling the surge's pigman sleeping feature?

### ISSUE THREAD

**Issue by darkhax** [TheRandomLabs/RandomTweaks#5]
Hi, I am one of the authors of Surge. Was wondering why you disable our fix to the pigman sleeping issue? If you would rather talk in private, rather than the issue tracker, feel free to join my [Discord Server](https://discord.gg/0zdMBNWIs0RNoWup)

**Comment by TheRandomLabs** [comment]
It's because I wanted to implement a sleep tweak as well, but it conflicted with Surge's pigman sleep fix. I just backported 1.12's sleep behavior, and added my tweak.
