### ISSUE TITLE
Suggestion: Add a way to blacklist animals from randomizedAges

### ISSUE THREAD

**Issue by Blatts12** [TheRandomLabs/RandomTweaks#52]
So i'm playing with Primitive Mobs and Traveling Merchants can spawn as a baby.

https://i.imgur.com/f4UVc51.png

**Comment by TheRandomLabs** [comment]
I'll put this in the next release.

**Comment by TheRandomLabs** [comment]
Sorry for the delay; I kinda forgot this existed.
