### ISSUE TITLE
Singleplayer player always spawning at 0,0 in void islands

### ISSUE THREAD

**Issue by Blue-Beaker** [TheRandomLabs/RandomTweaks#54]
I created a void islands world for survival in singleplayer but every time I enter the world the player spawns at x=0,z=0 regardless of where the player was at the last time.
Minecraft version:1.12.2
RandomTweaks version:1.12.2-2.7.1.0
Forge version:14.23.5.2838

**Comment by TheRandomLabs** [comment]
Whoa, this still isn't fixed? I'll look at it soon.

**Comment by TheRandomLabs** [comment]
"Soon" being five months later. :P
This is fixed in 1.12.2-2.8.0.0.
