### ISSUE TITLE
Squids are spawning in a very bugged manner.

### ISSUE THREAD

**Issue by SuperSoldier1337** [TheRandomLabs/RandomTweaks#55]
This mod is bugging squids to only spawn northwest of the player along with them almost never spawning with other aquatic mob adding mods present. In roguelike dungeons and adventures or other modpacks squids will almost never spawn.

**Comment by TheRandomLabs** [comment]
Could you try setting `squids.maxPackSize` to a higher value?

**Comment by TheRandomLabs** [comment]
Let me know if this is still an issue.
