### ISSUE TITLE
java.lang.StackOverflowError when creating/loading world with Industrial magic ic2 installed

### ISSUE THREAD

**Issue by raymanfanguy** [TheRandomLabs/RandomTweaks#56]
here's my crash report and mod list if needed...

[crash-2020-01-03_21.18.02-server.txt](https://github.com/TheRandomLabs/RandomTweaks/files/4021474/crash-2020-01-03_21.18.02-server.txt)
[ModList.txt](https://github.com/TheRandomLabs/RandomTweaks/files/4021475/ModList.txt)

**Comment by TheRandomLabs** [comment]
This is a problem with Industrial Magic. Rumaruka/Industrial-Magic---Crossover#13
