### ISSUE TITLE
[Suggestion] Compatibility with Natural Nether Portals

### ISSUE THREAD

**Issue by pimalel233** [TheRandomLabs/RandomTweaks#57]
Hi,
currently when disableNetherPortalCreation is set to true, no portal generated by NNP will be activated, they will just spawn with fire in one block. Also when setting it to false and modyfing canBeActivatedByFire false in RandomPortals mod, the result will be same. Obviously.
It would be cool, if it would be possible to keep disableNetherPortalCreation=true in RandomTweaks and yet allow only this mod to generate portals to enable creation of worlds where only access to that dimension is though using NNP portals [disabling its own creation for players].

Using:
Natural Nether Portals 1.2.0
Forge 14.23.5.2838
RandomConfigs 1.3.2.3
RandomTweaks 2.7.1.0
RandomPortals 1.8.1.1

**Comment by TheRandomLabs** [comment]
This would be easier if Natural Nether Portals fully spawned the Nether portals instead of just placing a fire block. Sorry for the wait. :P
