### ISSUE TITLE
FOV changes is bugged

### ISSUE THREAD

**Issue by jepotter1-archive** [TheRandomLabs/RandomTweaks#58]
- When it says "FOV changes enabled" it is actually disabled.
- When it says "FOV changes disabled" there are sporadic FOV changes when sprinting.

---

- **RandomTweaks version:** 2.7.1.0
- **Minecraft version:** 1.12.2
- **Modpack:** Project Gear

**Comment by BecksIsAlreadyTaken** [comment]
same with me. do you have numina installed?

**Comment by ghost** [comment]
Custom pack, 1.12.2, RandomTweaks 2.7.10 . Can't reproduce the issue.

**Comment by TheRandomLabs** [comment]
Another mod may be adjusting the FoV. I'm not sure what I can do about that.
