### ISSUE TITLE
[v1.7.0.1] SMP crash on startup

### ISSUE THREAD

**Issue by OrdinatorStouff** [TheRandomLabs/RandomTweaks#6]
http://pastebin.com/zaN1VJG1

RandomTweaks: 1.7.0.1
FML: 2239 (MC 1.10.2)

Server will not start, crashes during FMLConstructionEvent.

**Comment by TheRandomLabs** [comment]
Oh, that's a mistake I made. Really sorry for the inconvenience. Will be fixed in 1.7.0.2.

**Comment by OrdinatorStouff** [comment]
Not sure if I'm doing something wrong on my end but it seems that 1.7.0.2 is still crashing on server initialization: http://pastebin.com/HxrxXan6

**Comment by TheRandomLabs** [comment]
*sigh* I accidentally included a part of code in the release that I wasn't meant to. Sorry about that.

**Comment by TheRandomLabs** [comment]
I hope I don't end up having to make a 1.7.0.4.
