### ISSUE TITLE
[Suggestion/Issue] StepUp with JumpBoost issues

### ISSUE THREAD

**Issue by ghost** [TheRandomLabs/RandomTweaks#60]
Steps to reproduce(MC 1.12.2, RT 2.7.10):

- 2 block high wall, Jump Boost 1 pot.
- Vanilla AutoJump/Vanilla no autojump/Standalone StepUp do nothing and simply allow you to jump 2 blocks 
- RandomTweaks StepUp tries to StepUp as soon as your character reaches the first block, jerking the camera

If possible, please either fix the issue or provide an option to disable the ability to stepup mid-jump.

**Comment by TheRandomLabs** [comment]
In 1.12.2-2.8.0.0, there is an option to prevent Jump Boost from affecting stepup.
