### ISSUE TITLE
Potion Core Reach attribute fix for attack range is broken by random tweaks.

### ISSUE THREAD

**Issue by Darkmega18** [TheRandomLabs/RandomTweaks#61]
I've been testing with PotionCore-1.9, and a handful of mods which apply block mining/reach attribute based range increases, including corail tombstone (reach scroll), random things (spectre tools), cyclic (block reach enchant) and potion core itself (reach potion). 

I only knew of the feature when someone told me it was meant to be a thing, cause I hadn't known of it cause in my main modpack, timeless technician it's already broken. But in my test world in a side profile that I use for testing stuff and troubleshooting bugs quicker with the mentioned things and some other basics, once random tweaks is introduced the range increase I should get thanks to the attribute fix in potion core is broken and my attack range reverts to standard attack ranges despite being able to reach blocks and mobs originally at over 19 blocks far.
![image](https://user-images.githubusercontent.com/8104689/80299838-e7cfd880-87da-11ea-9723-54c915777d6d.png)

as soon as random tweaks came back out, my reach was back to working. So, I'm sorry but I'm pointing the finger and asking if you can figure out what it is that you're tweaking that could be causing an issue here? It's a cool feature I would quite like to continue existing.

**Comment by TheRandomLabs** [comment]
With just RandomTweaks and Potion Core, the Reach effect works perfectly for me.
![image](https://user-images.githubusercontent.com/16755704/80896574-0b42d800-8d33-11ea-8b12-e4ddc3dac746.png)
This is most likely a compatibility issue with another mod.

**Comment by Darkmega18** [comment]
you just showed me reach effect **MINING**. that's a picture of you aiming and mining. **_it's the reach effect for COMBAT_**, for **_hitting a mob_**, that you're negating. 

Tmtravlr told me it was something potentially to do with overriding or making your own right/left click events or something. I was to suspect cause of your changes that change your base melee attack rate and setting your hardcoded default reach which is overriding her changes.

With reach engaged you should be able to punch mobs from further away also with potion core installed. but with both this and totemic installed the reach affecting melee range fix is broken.

**Comment by TheRandomLabs** [comment]
Ah, thank you for clarifying.

**Comment by TheRandomLabs** [comment]
It was the night vision tweaks. RandomTweaks was replacing Potion Core's `EntityRenderer` with its own. They're now disabled when Potion Core is installed. :)

**Comment by Darkmega18** [comment]
Thank you for looking into it. Thats one down then. :) I'll test it next time it's uploaded.

now I just gotta pray that totemic will eventually reply. T_T

**Comment by TheRandomLabs** [comment]
Ah, I forgot about the other mods. See if disabling the night vision tweaks
in the config fixes it.

**Comment by Darkmega18** [comment]
OMG! IT WORKS WITH THE NIGHT VISION TURNED OFF. I need to report this to tmtravlr and ask whats the link to her reach and night vision then. cause I would have never guessed that was the issue until you fixed yours with it. holy crap. THANK YOU.

**Comment by TheRandomLabs** [comment]
I've already explained above, but it's because we're both replacing the
EntityRenderer. To work around this, I'd have to use a coremod, which
probably wouldn't be worth my effort.
