### ISSUE TITLE
randomizedAges blacklist isn't working

### ISSUE THREAD

**Issue by ghost** [TheRandomLabs/RandomTweaks#63]
When attempting to add anything to the blacklist section of "randomizedAges" it is not registered or saved into the config, seemingly all other config options are saving their changes properly except for the "randomizedAges blacklist."

Forge - 14.23.5.2847
RandomTweaks - 2.7.1.0

This happens even when the mod is isolated by itself.

**Comment by TheRandomLabs** [comment]
It's working fine for me.
![image](https://user-images.githubusercontent.com/16755704/80896037-725d8e00-8d2d-11ea-813a-bff2e91bfff7.png)
Can I ask what registry names you're using?
