### ISSUE TITLE
Breaking Custom Achievements 

### ISSUE THREAD

**Issue by Mattabase** [TheRandomLabs/RandomTweaks#9]
https://github.com/davqvist/CustomAchievements/issues/6#issuecomment-314540350

**Comment by davqvist** [comment]
Let me know if you need some info from me

**Comment by TheRandomLabs** [comment]
Sorry about taking so long; I was doing other things. I'm going to start working on this once Forge's website stops throwing a 502 Bad Gateway error (which can be seen [http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.11.2-13.20.1.2414/forge-1.11.2-13.20.1.2414-changelog.txt](here), unless it's just me).

**Comment by davqvist** [comment]
I can open the changelog just fine

**Comment by TheRandomLabs** [comment]
Oh, it's working for me now.

**Comment by TheRandomLabs** [comment]
I think I've fixed it.
